#!/bin/bash

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ]; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

setxkbmap fr -variant latin9 -option "caps:escape" -option "terminate:ctrl_bksp"
export QT_QPA_PLATFORMTHEME=qt5ct

$HOME/.local/bin/screen_layout.sh &
autocutsel -selection PRIMARY -fork &
picom > /dev/null 2> /dev/null &
feh --no-fehbg --bg-scale $(readlink $XDG_CONFIG_HOME/wallpaper) &
dunst &
[[ $(pgrep emacs) ]] && systemctl --user start emacs

if [[ $2 = "openbox" || $2 = "/usr/bin/openbox" ]]; then
	$XDG_CONFIG_HOME/polybar/launch.sh openbox &
	exec openbox-session
elif [[ $2 = "spectrwm" || $2 = "/usr/bin/spectrwm" ]]; then
	exec spectrwm
elif [[ $2 = "dwm" ]]; then
	exec dwm
fi

kill $(pgrep dunst)
kill $(pgrep picom)
kill $(pgrep polybar)
kill $(pgrep autocutsel)
