#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

setxkbmap fr -variant latin9 -option "caps:escape" -option "terminate:ctrl_bksp"

autocutsel -fork &
autocutsel -selection PRIMARY -fork &
feh --no-fehbg --bg-scale $(readlink $XDG_CONFIG_HOME/wallpaper) &
albert > /dev/null 2> /dev/null &
export QT_QPA_PLATFORMTHEME=qt5ct
xrandr --output DVI-D-1 --mode 1920x1080 --primary
xrandr --output HDMI-1 --mode 1920x1080 --right-of DVI-D-1
picom > /dev/null 2> /dev/null &

exec spectrwm
